
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  #type: LoadBalancer
  type: NodePort
