---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kaniko-demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: <repo>/<tag>
        ports:
        - containerPort: 80
