apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: kaniko-demo
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  #type: LoadBalancer
  type: Nodeport
