apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: hbstarjason/skaffold-demo
    workspaces: .
deploy:
  kubectl:
    manifests:
    - paths:
      - k8s-*
      parameters:
        IMAGE_NAME: hbstarjason/skaffold-demo
